name: ml-lncRNA
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - anyio=4.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.14
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpathlib=0.20.0
  - colorama=0.4.6
  - comm=0.2.1
  - cuda-cccl_linux-64=12.6.77
  - cuda-cudart-dev_linux-64=12.6.77
  - cuda-cudart-static_linux-64=12.6.77
  - cuda-cudart_linux-64=12.6.77
  - cuda-nvrtc=12.6.85
  - cuda-version=12.6
  - cupy=13.3.0
  - cupy-core=13.3.0
  - cymem=2.0.10
  - cyrus-sasl=2.1.28
  - cython-blis=1.0.1
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.4
  - fastrlock=0.8.2
  - fontconfig=2.14.2
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - icu=73.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipywidgets=8.1.5
  - jedi=0.19.2
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - krb5=1.20.1
  - language-data=1.3.0
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.6.4.1
  - libcufft=11.3.0.4
  - libcups=2.4.2
  - libcurand=10.3.7.77
  - libcurl=8.9.1
  - libcusolver=11.7.1.2
  - libcusparse=12.5.4.2
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnsl=2.0.1
  - libnvjitlink=12.6.85
  - libopenblas=0.3.28
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=2.0.4
  - mysql=8.4.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - openldap=2.6.4
  - openssl=3.4.0
  - overrides=7.4.0
  - packaging=24.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=24.2
  - platformdirs=3.10.0
  - ply=3.11
  - preshed=3.0.9
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=75.1.0
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - smart-open=7.0.5
  - smart_open=7.0.5
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - thinc=8.3.2
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - weasel=0.4.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - alabaster==1.0.0
      - arrow==1.3.0
      - arxiv==2.1.3
      - babel==2.16.0
      - bibtexparser==1.4.2
      - blis==1.0.2
      - branca==0.8.0
      - confection==0.1.5
      - contourpy==1.3.1
      - cycler==0.12.1
      - de-core-news-lg==3.8.0
      - de-core-news-md==3.8.0
      - de-core-news-sm==3.8.0
      - deprecated==1.2.15
      - docutils==0.21.2
      - en-core-web-md==3.8.0
      - en-core-web-sm==3.8.0
      - es-core-news-sm==3.8.0
      - fake-useragent==2.0.3
      - feedparser==6.0.11
      - folium==0.19.2
      - fonttools==4.55.3
      - free-proxy==1.1.3
      - geographiclib==2.0
      - geopandas==1.0.1
      - geopy==2.4.1
      - imagesize==1.4.1
      - joblib==1.4.2
      - jsonpickle==4.0.1
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - lxml==5.3.0
      - marisa-trie==1.2.1
      - matplotlib==3.10.0
      - murmurhash==1.0.11
      - networkx==3.4.2
      - numpy==2.0.2
      - outcome==1.3.0.post0
      - pandas==2.2.3
      - pillow==11.0.0
      - plotly==5.24.1
      - pyarrow==18.1.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pygments==2.18.0
      - pyogrio==0.10.0
      - pyparsing==3.2.0
      - pyproj==3.7.0
      - python-dotenv==1.0.1
      - pyvis==0.3.2
      - scholarly==1.7.11
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - selenium==4.27.1
      - sgmllib3k==1.0.0
      - shapely==2.0.6
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - srsly==2.5.0
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - trio==0.27.0
      - trio-websocket==0.11.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wasabi==1.1.3
      - wsproto==1.2.0
      - xyzservices==2024.9.0
